# Netlify configuration for admin dashboard deployment
[build]
  base = "/"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all admin routes to the Next.js app
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# SPA fallback for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Environment variables (you'll set these in Netlify dashboard)
[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

[context.deploy-preview.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
